services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: advanced-file-management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./.volumes/db:/var/lib/postgresql/data
